import {TextDataCharacterDataInput} from "../data_components/TextDataCharacterDataInput.js";
import {CheckboxCharacterDataInput} from "../data_components/CheckboxCharacterDataInput.js";
import {PositiveIntegerCharacterDataInput} from "../data_components/PositiveIntegerCharacterDataInput.js";

export class CyberneticsPane extends React.Component {
	render() {
		return React.createElement('div', {id:"cybernetics-pane", className:"pane"},
			React.createElement('div', {id:"cybernetics-part", className:"cybernetics-grid"},
				React.createElement('div', {className:"cybernetics-center-image"}, React.createElement('img', {src:'static-image://images/cybernetics.png'})),
				React.createElement('div', null, 
					React.createElement('div', {id:"cybernetics-eyes-name"}, "Eyes"),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "eyes", "make"], id:"cybernetics-eyes-make", name:"Make/Model"})),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "eyes", "bonus"], id:"cybernetics-eyes-bonus", name:"Bonus"})),
					React.createElement('div', null, React.createElement(CheckboxCharacterDataInput, {characterDataPath: ["cybernetics", "eyes", "functional"], id: "cybernetics-eyes-functional", name: "Functional"})),
					React.createElement('div', null, React.createElement(PositiveIntegerCharacterDataInput, {characterDataPath: ["cybernetics", "eyes", "cost"], id: "cybernetics-eyes-cost", name: "Cost"})),
				),
				React.createElement('div', null, 
					React.createElement('div', {id:"cybernetics-eyes-name"}, "Head"),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "head", "make"], id:"cybernetics-head-make", name:"Make/Model"})),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "head", "bonus"], id:"cybernetics-head-bonus", name:"Bonus"})),
					React.createElement('div', null, React.createElement(CheckboxCharacterDataInput, {characterDataPath: ["cybernetics", "head", "functional"], id: "cybernetics-head-functional", name: "Functional"})),
					React.createElement('div', null, React.createElement(PositiveIntegerCharacterDataInput, {characterDataPath: ["cybernetics", "head", "cost"], id: "cybernetics-head-cost", name: "Cost"})),
				),
				React.createElement('div', null, 
					React.createElement('div', {id:"cybernetics-eyes-name"}, "Torso"),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "torso", "make"], id:"cybernetics-torso-make", name:"Make/Model"})),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "torso", "bonus"], id:"cybernetics-torso-bonus", name:"Bonus"})),
					React.createElement('div', null, React.createElement(CheckboxCharacterDataInput, {characterDataPath: ["cybernetics", "torso", "functional"], id: "cybernetics-torso-functional", name: "Functional"})),
					React.createElement('div', null, React.createElement(PositiveIntegerCharacterDataInput, {characterDataPath: ["cybernetics", "torso", "cost"], id: "cybernetics-torso-cost", name: "Cost"})),
				),
				React.createElement('div', null, 
					React.createElement('div', {id:"cybernetics-eyes-name"}, "Chest"),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "chest", "make"], id:"cybernetics-chest-make", name:"Make/Model"})),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "chest", "bonus"], id:"cybernetics-chest-bonus", name:"Bonus"})),
					React.createElement('div', null, React.createElement(CheckboxCharacterDataInput, {characterDataPath: ["cybernetics", "chest", "functional"], id: "cybernetics-chest-functional", name: "Functional"})),
					React.createElement('div', null, React.createElement(PositiveIntegerCharacterDataInput, {characterDataPath: ["cybernetics", "chest", "cost"], id: "cybernetics-chest-cost", name: "Cost"})),
				),
				React.createElement('div', null, 
					React.createElement('div', {id:"cybernetics-eyes-name"}, "Hand"),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "hand", "make"], id:"cybernetics-hand-make", name:"Make/Model"})),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "hand", "bonus"], id:"cybernetics-hand-bonus", name:"Bonus"})),
					React.createElement('div', null, React.createElement(CheckboxCharacterDataInput, {characterDataPath: ["cybernetics", "hand", "functional"], id: "cybernetics-hand-functional", name: "Functional"})),
					React.createElement('div', null, React.createElement(PositiveIntegerCharacterDataInput, {characterDataPath: ["cybernetics", "hand", "cost"], id: "cybernetics-hand-cost", name: "Cost"})),
				),
				React.createElement('div', null, 
					React.createElement('div', {id:"cybernetics-eyes-name"}, "Arm"),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "arm", "make"], id:"cybernetics-arm-make", name:"Make/Model"})),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "arm", "bonus"], id:"cybernetics-arm-bonus", name:"Bonus"})),
					React.createElement('div', null, React.createElement(CheckboxCharacterDataInput, {characterDataPath: ["cybernetics", "arm", "functional"], id: "cybernetics-arm-functional", name: "Functional"})),
					React.createElement('div', null, React.createElement(PositiveIntegerCharacterDataInput, {characterDataPath: ["cybernetics", "arm", "cost"], id: "cybernetics-arm-cost", name: "Cost"})),
				),
				React.createElement('div', null, 
					React.createElement('div', {id:"cybernetics-eyes-name"}, "Lower Leg"),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "lowerLeg", "make"], id:"cybernetics-lowerLeg-make", name:"Make/Model"})),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "lowerLeg", "bonus"], id:"cybernetics-lowerLeg-bonus", name:"Bonus"})),
					React.createElement('div', null, React.createElement(CheckboxCharacterDataInput, {characterDataPath: ["cybernetics", "lowerLeg", "functional"], id: "cybernetics-lowerLeg-functional", name: "Functional"})),
					React.createElement('div', null, React.createElement(PositiveIntegerCharacterDataInput, {characterDataPath: ["cybernetics", "lowerLeg", "cost"], id: "cybernetics-lowerLeg-cost", name: "Cost"})),
				),
				React.createElement('div', null, 
					React.createElement('div', {id:"cybernetics-eyes-name"}, "Upper Leg"),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "upperLeg", "make"], id:"cybernetics-upperLeg-make", name:"Make/Model"})),
					React.createElement('div', null, React.createElement(TextDataCharacterDataInput, {characterDataPath: ["cybernetics", "upperLeg", "bonus"], id:"cybernetics-upperLeg-bonus", name:"Bonus"})),
					React.createElement('div', null, React.createElement(CheckboxCharacterDataInput, {characterDataPath: ["cybernetics", "upperLeg", "functional"], id: "cybernetics-upperLeg-functional", name: "Functional"})),
					React.createElement('div', null, React.createElement(PositiveIntegerCharacterDataInput, {characterDataPath: ["cybernetics", "upperLeg", "cost"], id: "cybernetics-upperLeg-cost", name: "Cost"})),
				),
			),
		)
	}
}